# Generated by Django 5.1.4 on 2024-12-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_hashed_password_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
