# Generated by Django 5.1.4 on 2024-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_shipper',
        ),
    ]
