# Generated by Django 5.1.4 on 2025-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_full_name_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
