# Generated by Django 5.1.6 on 2025-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_code_expiration_users_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_passport_uploaded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='passport_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
