# Generated by Django 5.1.6 on 2025-04-28 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_is_passport_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pid',
            name='picture',
        ),
        migrations.AddField(
            model_name='pid',
            name='pid_picture',
            field=models.ImageField(default=1, upload_to='pid_pictures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pid',
            name='pid_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='pid_selfies/'),
        ),
        migrations.AddField(
            model_name='pid',
            name='pid_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pid',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 12, 30, 37, 734570)),
        ),
    ]
