# Generated by Django 5.1.6 on 2025-04-28 17:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_pid_picture_pid_pid_picture_pid_pid_selfie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pid',
            name='pid_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pid',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 12, 34, 9, 927474)),
        ),
    ]
