# Generated by Django 5.1.6 on 2025-04-28 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pid_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pid',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 13, 17, 14, 928879)),
        ),
    ]
