# Generated by Django 5.1.6 on 2025-05-03 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pid_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pid',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 2, 11, 31, 26, 575734)),
        ),
    ]
