# Generated by Django 5.2.4 on 2025-08-12 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pid_expiration_date_bankcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pid',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 11, 12, 41, 40, 572320)),
        ),
    ]
