# Generated by Django 5.1.6 on 2025-07-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pid_expiration_date_bankcard_and_more'),
        ('users', '0011_users_balance_alter_pid_expiration_date'),
    ]

    operations = [
    ]
