# Generated by Django 5.1.4 on 2025-01-06 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_country_remove_airport_location_and_more'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sender',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departing_flights',
                to='locations.airport'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='publisher',
            field=models.CharField(
                choices=[('airline', 'Airline'), ('custom', 'Custom Flight')],
                default='airline',  # Provide a valid default
                max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arriving_flights',
                to='locations.airport'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='available_space',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='available_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('taken', 'Taken'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled')
                ],
                default='available',
                max_length=20
            ),
        ),
        migrations.CreateModel(
            name='UserFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_flights',
                    to='offers.flight'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_flights',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='user_flight',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='offers.userflight'
            ),
            preserve_default=False,
        ),
    ]

