# Generated by Django 5.1.4 on 2025-01-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_country_remove_airport_location_and_more'),
        ('offers', '0002_remove_flight_date_remove_flight_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='locations.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='publisher',
            field=models.CharField(choices=[('airline', 'Airline'), ('custom', 'Custom Flight')], default='airline', max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='locations.airport'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_space',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='available_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
