# Generated by Django 5.1.4 on 2025-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
    ]
