# Generated by Django 5.1.4 on 2025-01-06 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_country_remove_airport_location_and_more'),
        ('offers', '0004_populate_flight_offer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='locations.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='locations.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_flight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.userflight'),
            preserve_default=False,
        ),
    ]
