# Generated by Django 5.1.4 on 2025-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
