# Generated by Django 5.1.4 on 2025-01-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemcategory_item_category'),
        ('offers', '0007_flight_creator_flight_details_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
        ),
    ]
