# Generated by Django 5.1.4 on 2025-01-15 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_remove_item_category_and_more'),
        ('offers', '0008_offer_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='allow_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='available_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='preferred_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemcategory'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
