# Generated by Django 5.1.4 on 2025-01-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_remove_item_category_and_more'),
        ('offers', '0009_remove_offer_category_id_offer_allow_fragile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='preferred_category',
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='items.itemcategory'),
        ),
    ]
