# Generated by Django 5.1.4 on 2025-01-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_remove_item_category_and_more'),
        ('offers', '0010_remove_offer_preferred_category_offer_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='allow_fragile',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='available_dimensions',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='categories',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(choices=[('airline', 'Airline'), ('custom', 'Custom Flight')], default='airline', max_length=50),
        ),
    ]
