# Generated by Django 5.1.4 on 2025-01-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_remove_offer_allow_fragile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='allow_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='available_dimensions',
            field=models.CharField(default='0x0x0', max_length=50),
        ),
    ]
