# Generated by Django 5.1.4 on 2025-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_icon_itemcategory_icon_path'),
        ('offers', '0012_offer_allow_fragile_offer_available_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', to='items.itemcategory'),
        ),
    ]
