# Generated by Django 5.1.6 on 2025-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_is_pictures_uploaded'),
        ('offers', '0014_remove_offer_categories_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='offers', through='offers.OfferCategory', to='items.itemcategory'),
        ),
    ]
