# Generated by Django 5.1.4 on 2025-01-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_volume_item_created_at_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
    ]
