# Generated by Django 5.1.4 on 2025-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemcategory_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
