# Generated by Django 5.1.4 on 2025-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='icon',
            field=models.CharField(default='default_icon.svg', max_length=255),
        ),
    ]
