# Generated by Django 5.1.4 on 2025-01-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemcategory_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='icon',
            new_name='icon_path',
        ),
    ]
