# Generated by Django 5.1.6 on 2025-03-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_icon_itemcategory_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
