# Generated by Django 5.1.6 on 2025-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_pictures_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
