# Generated by Django 5.1.6 on 2025-03-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_is_pictures_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempicture',
            name='image_path',
        ),
        migrations.AddField(
            model_name='itempicture',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='item_pictures/'),
        ),
    ]
