# Generated by Django 5.1.6 on 2025-03-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_itempicture_image_path_itempicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='items.item'),
        ),
    ]
