# Generated by Django 5.1.6 on 2025-04-12 16:39

import azure_storage_handler.storages
import azure_storage_handler.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_itempicture_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='image',
            field=models.ImageField(default='default_item.jpg', storage=azure_storage_handler.storages.AzureItemImageStorage(), upload_to=azure_storage_handler.utils.item_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='items.item'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
