# Generated by Django 5.1.6 on 2025-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('in_process', 'In_process')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestpayment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('in_process', 'In_process')], default='pending', max_length=20),
        ),
    ]
