# Generated by Django 5.1.6 on 2025-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_requests', '0002_alter_request_status_alter_requestpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
