# Generated by Django 5.2.4 on 2025-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_requests', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='verification_code',
            field=models.CharField(blank=True, help_text='6-digit code for in-person verification', max_length=6, null=True),
        ),
    ]
