# Generated by Django 5.2.5 on 2025-08-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_requests", "0004_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="delivery_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="delivery_code_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="request",
            name="delivery_code_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="delivery_verification_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="request",
            name="delivery_verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="max_verification_attempts",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="request",
            name="pickup_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="pickup_code_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="request",
            name="pickup_code_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="pickup_verification_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="request",
            name="pickup_verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("in_process", "In_process"),
                    ("in_transit", "In_transit"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
