# Generated by Django 5.1.4 on 2025-01-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('city_abbr', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('city_name', models.CharField(max_length=255, unique=True)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('country_abbr', models.CharField(max_length=10, unique=True)),
                ('country_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='location',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='code',
            new_name='airport_code',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='name',
            new_name='airport_name',
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='locations.city'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('allowed_categories', 'Allowed Categories'), ('restricted_items', 'Restricted Items')], max_length=50)),
                ('policy_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('policy_description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='locations.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
