# Generated by Django 5.1.6 on 2025-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_country_remove_airport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_picture_url',
            field=models.URLField(default='https://ugogostorageaccount.blob.core.windows.net/airportimage/ZTZ', null=True),
        ),
    ]
